export default {
    GET_CURRENT_LOCATİON:"GET_CURRENT_LOCATİON",
    GET_INPUT:"GET_INPUT",
    TOGGLE_SEARCH_RESULT:"TOGGLE_SEARCH_RESULT",
    GET_ADRESS_PREDICTIONS:"GET_ADRESS_PREDICTIONS",
    GET_SELECTED_ADDRESS:"GET_SELECTED_ADDRESS",
    GET_DISTANCE_MATRIX:"GET_DISTANCE_MATRIX",
    GET_FARE:"GET_FARE",
    BOOK_CAR:"BOOK_CAR",
    GET_NEARBY_DRIVERS:"GET_NEARBY_DRIVERS",
    BOOKING_CONFIRMED:"BOOKING_CONFIRMED"
};